services:
  app:
    build: .
    container_name: codeigniter_spark
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_HOSTNAME: db
      DATABASE_NAME: codeigniter
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_DRIVER: PostgreSQL
    networks:
      minha_rede_estatica:
        ipv4_address: 172.25.0.10

  db:
    image: postgres:13
    container_name: codeigniter_db
    restart: always
    environment:
      POSTGRES_DB: codeigniter
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "6543:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - minha_rede_estatica

volumes:
  db_data:

networks:
  minha_rede_estatica:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16